### ISSUE TITLE
Delay on Click Commands

### ISSUE THREAD

**Issue by Cananbolt** [Natural-Harmonia-Gropius/InputEvent#32]
This script is an actual game-changer. Thank you for sharing it. I was just wondering if it is possible to reduce the delay on the click commands as it is quite noticeable. Every other command (double_click, release, and so on) works as intended with no delay, from what I can see. Thanks again for the awesome script.

**Comment by Natural-Harmonia-Gropius** [comment]
Since there are multiple possible actions there is no way for me to do this.
If there is any good idea or practical case I will try it.

About noticeable delay you can try `input-doubleclick-time=200` or lower value, maybe 150.

![image](https://user-images.githubusercontent.com/50797982/206666110-ee241828-2de3-488e-9fc6-299524877344.png)

**Comment by Cananbolt** [comment]
No problem. Your idea of lowering the `input-doubleclick-time` did the trick. I put it to 125, and there is a notable difference. Thank you so much! I'll go ahead and close the comment as this helped decreased the delay.
